# SetJointCurrentGainIFinger service
# Sets the current-loop I gain and integral limit for one finger (4 joints)

# Request
float32[4] current_gain_i  # Enter current-loop I gain for each joint
float32[4] current_i_limit  # Setting the current Integral Maximum for each joint
int32 finger_number  # Enter the finger number
---
# Response
int32 result  # DG_RESULT enum value
