# SetJointCurrentGainIAll service
# Sets the current-loop I gain and integral limit for all joints

# Request
float32[20] current_gain_i  # Enter current-loop I gain for all joints
float32[20] current_i_limit  # Setting the current Integral Maximum for all joints
---
# Response
int32 result  # DG_RESULT enum value
