# SetJointGainIBase service
# Sets the I-gain value and error integral maximum for the base joints (DG-4F)

# Request
float32[2] gain_i  # Enter the I gain for base joints
float32[2] i_limit  # Setting the Error Integral Maximum for base joints
---
# Response
int32 result  # DG_RESULT enum value
