# SetJointCurrentGainIBase service
# Sets the current-loop I gain and integral limit for the base joints (DG-4F)

# Request
float32[2] current_gain_i  # Enter current-loop I gain for base joints
float32[2] current_i_limit  # Setting the current Integral Maximum for base joints
---
# Response
int32 result  # DG_RESULT enum value
